fixes a broken projects link on the docs homepage
Open-Cap-Table-Coalition/Open-Cap-Format-OCF pull request #464
Opened 2024-02-14 20:23 UTC by osis

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The PROJECTS.md link on https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/ is a broken link. This PR points it to the correct page.

2024-02-26 20:23 UTC, JSv4 approved these changes
Thx

2024-02-26 20:26 UTC, JSv4 requested changes
Actually, on second thought, can we direct this to the projects page on the documentation website? Generally we don't want to direct people to the docs folder in the repo.

2024-02-26 20:26 UTC, JSv4 commented on docs/README.md
> +|             [PROJECTS.md](/Open-Cap-Format-OCF/PROJECTS/) | Collection of public projects in the OCF ecosystem listed in |
```suggestion
| [PROJECTS.md](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/PROJECTS/) | Collection of public projects in the OCF ecosystem listed in |
```

2024-02-27 01:52 UTC, osis commented
LGTM

2024-02-27 02:25 UTC, osis commented
On a second look, the original link I put in does indeed go to the documents page and not the file. It doesn't include the domain so it makes the path less brittle. Unless you saw something that I didn't @JSv4?

2024-06-24 14:03 UTC, closed without merging